pre-commit:
  commands:
    isort:
      files: git ls-files
      glob: '*.{py}'
      run: isort {staged_files}
      stage_fixed: true
    ruff:
      files: git ls-files
      glob: '*.py'
      run: ruff check {staged_files} --fix
    clean-jupyter:
      files: git ls-files
      glob: '*.ipynb'
      run: rye run jupyter nbconvert --clear-output --inplace {staged_files}
      stage_fixed: true
    mypy:
      glob: '*.py'
      run: mypy --pretty {staged_files} --ignore-missing-imports