services:
  calculator:
    build: .
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health && exit 0 || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 2
      start_period: 10s
    restart: unless-stopped

